FROM php:7.4-fpm-alpine3.11

RUN echo "ipv6" >> /etc/modules
RUN apk add git
RUN apk add --no-cache --virtual .phpize-deps $PHPIZE_DEPS && \
    apk add --no-cache --virtual .imagemagick-edge \
	    --repository http://dl-3.alpinelinux.org/alpine/v3.11/main/ \
	    --allow-untrusted \
	imagemagick \
	imagemagick-dev && \
    apk add --update --virtual .pecl-build-deps \
	icu-dev \
	curl-dev \
	freetype-dev \
	pcre-dev \
	postgresql-dev \
	libtool \
	libjpeg-turbo-dev \
	libpng-dev \
	oniguruma-dev \
	libxml2-dev && \
    apk add \
	git \
	curl \
	bash \
	bash-completion \
	icu \
	vim \
	pcre \
	sqlite \
	freetype \
	libintl \
	libjpeg-turbo \
	imagemagick \
	libpng \
	libxml2 \
	libzip-dev \
	mysql-client \
	nodejs && \
    export CFLAGS="$PHP_CFLAGS" CPPFLAGS="$PHP_CPPFLAGS" LDFLAGS="$PHP_LDFLAGS" && \
    pecl install \
	apcu \
	redis \
	zip \
	imagick-3.4.3 && \
    docker-php-ext-enable imagick && \
    docker-php-ext-enable redis && \
    docker-php-ext-enable apcu && \
	docker-php-ext-configure gd \
	--with-freetype \
	--with-jpeg && \
    docker-php-ext-configure bcmath && \
    docker-php-ext-install \
	soap \
	zip \
	curl \
	bcmath \
	exif \
	gd \
	iconv \
	intl \
	mbstring \
	pdo \
	pdo_mysql \
	mysqli \
	opcache && \
    apk del \
	.pecl-build-deps .phpize-deps

RUN docker-php-ext-enable mysqli

RUN apk add --update nodejs nodejs-npm
RUN npm install -g \
	less \
	bower \
	lesshint \
	uglify-js \
	coffeescript \
	uglifycss



RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

WORKDIR /app
COPY ./ /app

RUN composer install --prefer-dist --optimize-autoloader && \
    composer clear-cache
