version: '3.2'

services:
  nginx:
    #image: nginx:latest
    build:
      dockerfile: Dockerfile-nginx
      context: .
    ports:
      - "80:80"
      - "1080:1080"
    hostname: test.local
    networks:
      default:
        aliases:
          - backend.paradox.local
          - frontend.paradox.local
    extra_hosts:
      - "backend.paradox.local:127.0.0.1"
      - "frontend.paradox.local:127.0.0.1"
    links:
      - phpfpm
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/backend:/etc/nginx/conf.d/backend.conf
      - ./nginx/frontend:/etc/nginx/conf.d/frontend.conf
      - .:/app

  phpfpm:
    #image: dmstr/php-yii2:7.1-fpm-3.1-alpine-nginx-xdebug
    build:
      dockerfile: Dockerfile-fpm
      context: .
    ports:
      - "9000:9000"
      - "8880:8880"
    working_dir: /app
    volumes:
      - .:/app
    links:
      - mysql

  mysql:
    image: mariadb:10.2
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=123
    volumes:
      - ./data:/var/lib/mysql